---
- name: Create Node and Bucket eyeri
  hosts: tags_Name_eye*
  gather_facts: true
  become: true
  vars_files:
    - "vars.yaml"
  
  roles:
    - first_role
    - second_role
    - bucket_create
    - node_create
    - send_logs
    - good_job

