---
# tasks file for first_role
- name: add index file
  file:
    path: /var/www/html/index.html
    state: touch
- name: add text to index file
  lineinfile:
    path: /var/www/html/index.html
    line: <h1> Welcome to Ethan's Website! </h1>
